import Replicate from 'replicate'                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                   
const replicate = new Replicate({                                                                                                                                                                                  
  auth: process.env.REPLICATE_API_TOKEN,                                                                                                                                                                           
  userAgent: 'https://www.npmjs.com/package/create-replicate'                                                                                                                                                      
})                                                                                                                                                                                                                 
const model = 'stability-ai/stable-diffusion-3.5-large:e6c4657fe1b3f078fb26d68a1413bc8013e2b085504dd84a33e26e16fb95a593'                                                                                           
const input = {                                                                                                                                                                                                    
  cfg: 4.5,                                                                                                                                                                                                        
  steps: 40,                                                                                                                                                                                                       
  prompt: '~*~aesthetic~*~ #boho #fashion, full-body 30-something woman laying on microfloral grass, candid pose, overlay reads Stable Diffusion 3.5, cheerful cursive typography font',                           
  aspect_ratio: '1:1',                                                                                                                                                                                             
  output_format: 'webp',                                                                                                                                                                                           
  output_quality: 90,                                                                                                                                                                                              
  prompt_strength: 0.85,                                                                                                                                                                                           
}                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
console.log('Using model: %s', model)                                                                                                                                                                              
console.log('With input: %O', input)                                                                                                                                                                               
                                                                                                                                                                                                                   
console.log('Running...')                                                                                                                                                                                          
const output = await replicate.run(model, { input })                                                                                                                                                               
console.log('Done!', output)    
