name: Deploy Node.js App

on:
  push:
    branches:
      - main  # Change this if you're using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Change if needed

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: echo "REPLICATE_API_TOKEN=${{ secrets.REPLICATE_API }}" >> $GITHUB_ENV

      - name: Build and Start Server
        run: |
          npm run build  # Remove if no build step
          node index.js
