name: Deploy to Cloudways

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Deploy to Cloudways
      env:
        SSH_HOST: ${{ secrets.CLOUDWAYS_HOST }}
        SSH_USER: ${{ secrets.CLOUDWAYS_USER }}
        SSH_KEY: ${{ secrets.CLOUDWAYS_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
          cd /home/master/applications/YOUR_APP_NAME_HERE/public_html
          git pull origin main
          npm install
          pm2 restart index || pm2 start index.js --name "index"
        EOF
